//! The handlers: parsed arguments in, a view model out (FR-069).
//!
//! Each handler does the same four things and nothing else: builds a validated command
//! from what was typed; opens a unit of work; calls one use case of the application
//! layer; commits. Deciding is the application's business and showing is the renderer's.

pub mod audit;
pub mod completions;
pub mod config;
pub mod first_steps;
pub mod link;
pub mod workspace;

use trcli_application::governance::record::commit;
use trcli_application::outcome::Problem;

use crate::args::Commands;
use crate::cli::{Invocation, Parsed, command};
use crate::compose::{AppUnit, Session};
use crate::extension::Extension;
use crate::output::Reply;

/// Runs the command that was parsed.
pub async fn run(
    session: &mut Session,
    extension: &impl Extension,
    invocation: &Invocation,
) -> Result<Reply, Problem> {
    match &invocation.parsed {
        Parsed::Nothing => first_steps::run(session, &command(extension)).await,
        Parsed::Foundation(Commands::Completions(arguments)) => {
            Ok(completions::run(arguments, &mut command(extension)))
        }
        Parsed::Foundation(command) => foundation(session, command).await,
        // A command of a record kind is handed to the feature that owns the kind.
        Parsed::Kind { noun, matches } => extension.run(session, noun, matches).await,
    }
}

/// Runs one of the foundation's own commands.
async fn foundation(session: &mut Session, command: &Commands) -> Result<Reply, Problem> {
    match command {
        Commands::Init(arguments) => workspace::init(session, arguments).await,
        Commands::Workspace(command) => workspace::run(session, command).await,
        Commands::Config(command) => config::run(session, command).await,
        Commands::Link(command) => link::run(session, command).await,
        Commands::Tag(command) => link::tags(session, command).await,
        Commands::Audit(command) => audit::run(session, command).await,
        Commands::Telemetry(command) => audit::telemetry(session, command).await,
        // Handled above, where the whole command tree is at hand.
        Commands::Completions(_) => {
            Err(Problem::internal("completions are generated by the caller"))
        }
    }
}

/// Commits a unit of work and stores the new end of the audit trail.
pub async fn finish(session: &Session, unit: AppUnit) -> Result<(), Problem> {
    commit(unit, &session.head()?).await
}
